server:
  port: 8001

spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@mtvsdbserver_high?TNS_ADMIN=./src/main/resources/database/Wallet_mtvsDBServer
    username: Mylittletales
    password: mtvsNetwork12
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  #      location: C:/Users/HP/Desktop/AIproject/
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: true
  freemarker:
    cache: false
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    check-template-location: true
  web:
    resources:
      static-locations: classpath:/upload/

image:
  image-dir: src/main/resources

mybatis:
  mapper-locations: mybatis/mappers/*.xml
  type-aliases-package: com.network.mylittletale
  configuration:
    map-underscore-to-camel-case: true
