server:
  port: 8001

spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@mtvsdbserver_high?TNS_ADMIN=/Wallet_mtvsDBServer
    username: Mylittletales
    password: mtvsNetwork12
