server:
  port: 8001

spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@mtvsdbserver_high?TNS_ADMIN=./database/Wallet_mtvsDBServer/
    username: admin
    password: MTVSnetwork12

mybatis:
  mapper-locations: mappers/**/*.xml
